repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: double-quote-string-fixer
  - repo: https://github.com/PyCQA/bandit
    rev: master
    hooks:
      - id: bandit
  - repo: https://github.com/PyCQA/flake8
    rev: master
    hooks:
      - id: flake8
