repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
      - id: double-quote-string-fixer
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: system
        entry: flake8 .
      - id: bandit
        name: bandit
        language: system
        entry: bandit -r . -lll
        files: \.py
