name: macOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          brew update
          brew install ykpers libyubikey libusb swig
          python -m pip install --upgrade pip
          pip install .

      - name: Run unit tests
        run: python setup.py test

      - name: Run CLI
        run: |
          ykman --version
          [[ -z "$(ykman --version | grep -E "not found|missing")" ]]
