name: usbip-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: List kernel modules
        run: lsmod

      - name: Try usbip
        run: |
          usbip version
          usbip help
          usbip list --local

      - name: List remote devices
        run: |
          usbip list --remote=emlun.se

      - name: Attach remote device
        run: |
          usbip attach --remote=emlun.se -b 1-2.1.4

      - name: Detach remote device
        run: |
          usbip detach --remote=emlun.se -b 1-2.1.4
