name: usbip-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: List kernel modules
        run: lsmod

      - name: Try usbip
        run: |
          usbip version
          usbip help
          usbip list --local
